version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8199"
    restart: always
    volumes:
      - ./config/config.toml:/apps/config/config.toml
      - ./data/logs:/logs
      - ./data/upload:/tmp/upload
    environment:
      - TZ=Asia/Shanghai
    depends_on:
       - mysql
       - redis
    networks:
       - backend
  mysql:
     image: mysql:5.7
     ports:
       - "3310:3306"
     restart: always
     environment:
       MYSQL_DATABASE: cc_main
#       MYSQL_USER: appadmin
#       MYSQL_PASSWORD: appadmin
       MYSQL_ROOT_PASSWORD: LxXgw7DS59WoAfk1
       TZ: Asia/Shanghai
     volumes:
       - ./data/mysql:/var/lib/mysql
     networks:
       - backend
  redis:
     image: redis
     command: ["redis-server","--requirepass","LxXgw.redis.WoAfk1","--save","60","1"]
     hostname: redis
     environment:
       - TZ=Asia/Shanghai
     ports:
       - "6400:6379"
     volumes:
       - ./data/redis:/data
     networks:
       - backend

networks:
  backend: